In [8]:
import json
import pandas as pd

In [3]:
with open('Data/Match_info/2017.json', 'r') as f:
    data = json.load(f)

# This is how the data for a single match look like

In [14]:
data['week_1']['match_1']

{'carries1': '122',
 'carries2': '102',
 'clean_breaks1': '8',
 'clean_breaks2': '16',
 'conversion_accuracy1': '50.0%',
 'conversion_accuracy2': '85.7%',
 'conversions1': '2',
 'conversions2': '7',
 'defenders_beaten1': '19',
 'defenders_beaten2': '26',
 'drop_goal_accuracy1': '-',
 'drop_goal_accuracy2': '-',
 'drop_goals1': '0',
 'drop_goals2': '0',
 'kicks_in_play1': '19',
 'kicks_in_play2': '32',
 'lineouts_lost1': '4',
 'lineouts_lost2': '2',
 'lineouts_won1': '9',
 'lineouts_won2': '6',
 'mauls_won1': '0',
 'mauls_won2': '1',
 'meters_carried1': '456',
 'meters_carried2': '525',
 'missed_tackels1': '26',
 'missed_tackels2': '19',
 'offloads1': '8',
 'offloads2': '7',
 'passes1': '185',
 'passes2': '108',
 'penalties_conceded1': '5',
 'penalties_conceded2': '11',
 'penalty_goal_accuracy1': '50.0%',
 'penalty_goal_accuracy2': '100.0%',
 'penalty_goals1': '4',
 'penalty_goals2': '3',
 'red_cards1': '0',
 'red_cards2': '0',
 'rucks_lost1': '6',
 'rucks_lost2': '3',
 'rucks_won1': '80',
 'rucks_won2': '60',
 'score1': '18',
 'score2': '56',
 'scrums_lost1': '0',
 'scrums_lost2': '0',
 'scrums_won1': '3',
 'scrums_won2': '8',
 'tackles1': '88',
 'tackles2': '118',
 'team1': 'Rebels',
 'team1_25': '3.7%',
 'team1_40': '18.9%',
 'team1_op_25': '5.8%',
 'team1_op_40': '24.2%',
 'team2': 'Blues',
 'team2_25': '7.9%',
 'team2_40': '9.5%',
 'team2_op_25': '7.9%',
 'team2_op_40': '22.1%',
 'tries1': '2',
 'tries2': '7',
 'turnovers_conceded1': '22',
 'turnovers_conceded2': '14',
 'turnovers_won1': '5',
 'turnovers_won2': '10',
 'yellow_cards1': '0',
 'yellow_cards2': '1'}

In [176]:
match_dfs = []

for s in range(2012,2018):
    with open('Data/Match_info/'+str(s)+'.json', 'r') as f:
        data = json.load(f)
    
    for w in data:
        for m in data[w]:
            match_info = data[w][m]
            match_info['season'] = str(s)
            match_info['week'] = w
            match_info['match'] = m
            match_dfs.append(pd.DataFrame(match_info, index=[0]))

In [177]:
super_rugby_data = pd.concat(match_dfs)

In [178]:
super_rugby_data.groupby('season').size().reset_index()

  season    0
0   2012  120
1   2013  119
2   2014  120
3   2015  120
4   2016  135
5   2017  135

In [179]:
# missing out one match in 2013, because website is not responsive

In [180]:
pd.set_option('display.max_columns', 500)
super_rugby_data.head()

,carries1,carries2,clean_breaks1,clean_breaks2,conversion_accuracy1,conversion_accuracy2,conversions1,conversions2,defenders_beaten1,defenders_beaten2,drop_goal_accuracy1,drop_goal_accuracy2,drop_goals1,drop_goals2,kicks_in_play1,kicks_in_play2,lineouts_lost1,lineouts_lost2,lineouts_won1,lineouts_won2,match,mauls_won1,mauls_won2,meters_carried1,meters_carried2,missed_tackels1,missed_tackels2,offloads1,offloads2,overall_pos1,overall_pos2,passes1,passes2,penalties_conceded1,penalties_conceded2,penalty_goal_accuracy1,penalty_goal_accuracy2,penalty_goals1,penalty_goals2,red_cards1,red_cards2,rucks_lost1,rucks_lost2,rucks_won1,rucks_won2,score1,score2,scrums_lost1,scrums_lost2,scrums_won1,scrums_won2,season,tackles1,tackles2,team1,team1_25,team1_40,team1_op_25,team1_op_40,team2,team2_25,team2_40,team2_op_25,team2_op_40,tries1,tries2,turnovers_conceded1,turnovers_conceded2,turnovers_won1,turnovers_won2,week,yellow_cards1,yellow_cards2
0,110,85,8,7,50.0%,100.0%,2,1,13,18,0.0%,-,1,0,22,34,5,2,15,7,match_1,0,0,443,316,18,13,4,9,67.0%,33.0%,129,101,9,12,66.7%,66.7%,3,6,0,0,5,5,75,51,18,19,1,0,5,8,2012,74,115,Blues,NaN,NaN,NaN,NaN,Crusaders,NaN,NaN,NaN,NaN,2,1,18,14,0,0,week_1,0,0
0,69,132,11,1,0.0%,0.0%,2,1,15,10,-,0.0%,0,1,28,27,2,4,5,15,match_2,0,0,331,312,10,15,6,8,67.0%,33.0%,79,144,11,10,42.9%,66.7%,7,6,0,0,4,4,49,109,19,17,0,0,6,5,2012,146,61,Brumbies,NaN,NaN,NaN,NaN,Force,NaN,NaN,NaN,NaN,2,1,11,7,0,0,week_1,0,0
0,78,86,4,7,-,100.0%,0,1,17,17,100.0%,-,1,0,27,20,2,5,12,6,match_3,0,0,333,348,17,17,3,5,0.0%,100.0%,85,136,11,13,71.4%,40.0%,7,5,0,0,2,2,62,59,18,13,1,1,5,8,2012,95,96,Bulls,NaN,NaN,NaN,NaN,Sharks,NaN,NaN,NaN,NaN,0,1,16,8,0,0,week_1,0,0
0,107,162,5,4,100.0%,100.0%,1,2,10,13,-,-,0,0,19,16,3,2,13,10,match_4,0,0,430,413,14,10,14,12,33.0%,67.0%,112,200,10,12,100.0%,100.0%,4,3,0,0,8,7,69,127,19,23,0,0,6,6,2012,176,104,Chiefs,NaN,NaN,NaN,NaN,Highlanders,NaN,NaN,NaN,NaN,1,2,15,17,0,0,week_1,0,0
0,86,84,3,4,-,100.0%,0,1,7,13,0.0%,50.0%,1,2,16,21,5,1,10,4,match_5,0,0,304,259,13,7,9,5,0.0%,100.0%,130,125,12,17,81.8%,71.4%,11,7,0,0,6,6,65,70,27,25,0,1,4,5,2012,103,99,Lions,NaN,NaN,NaN,NaN,Cheetahs,NaN,NaN,NaN,NaN,0,1,14,12,0,0,week_1,0,2

In [181]:
super_rugby_data.reset_index(drop=True, inplace=True)

In [182]:
# handle missing data

In [183]:
# containin - as a string.
super_rugby_data.isin(['-']).any()[super_rugby_data.isin(['-']).any() == True]

conversion_accuracy1      True
conversion_accuracy2      True
drop_goal_accuracy1       True
drop_goal_accuracy2       True
penalty_goal_accuracy1    True
penalty_goal_accuracy2    True
dtype: bool

In [184]:
# All of the are accuracy when their were no attempt for conversion, drop goal or penalty
super_rugby_data = super_rugby_data.replace('-', '0.0%')

In [185]:
# containin Nan as a string.
super_rugby_data.isin(['NaN']).any()[super_rugby_data.isin(['NaN']).any() == True]

team1_25       True
team1_40       True
team1_op_25    True
team1_op_40    True
team2_25       True
team2_40       True
team2_op_25    True
team2_op_40    True
dtype: bool

In [186]:
# possentions of different sections of the field not available.
super_rugby_data = super_rugby_data.replace('NaN', '0.0%')

In [187]:
super_rugby_data.columns

Index(['carries1', 'carries2', 'clean_breaks1', 'clean_breaks2',
       'conversion_accuracy1', 'conversion_accuracy2', 'conversions1',
       'conversions2', 'defenders_beaten1', 'defenders_beaten2',
       'drop_goal_accuracy1', 'drop_goal_accuracy2', 'drop_goals1',
       'drop_goals2', 'kicks_in_play1', 'kicks_in_play2', 'lineouts_lost1',
       'lineouts_lost2', 'lineouts_won1', 'lineouts_won2', 'match',
       'mauls_won1', 'mauls_won2', 'meters_carried1', 'meters_carried2',
       'missed_tackels1', 'missed_tackels2', 'offloads1', 'offloads2',
       'overall_pos1', 'overall_pos2', 'passes1', 'passes2',
       'penalties_conceded1', 'penalties_conceded2', 'penalty_goal_accuracy1',
       'penalty_goal_accuracy2', 'penalty_goals1', 'penalty_goals2',
       'red_cards1', 'red_cards2', 'rucks_lost1', 'rucks_lost2', 'rucks_won1',
       'rucks_won2', 'score1', 'score2', 'scrums_lost1', 'scrums_lost2',
       'scrums_won1', 'scrums_won2', 'season', 'tackles1', 'tackles2', 'team1',
       'team1_25', 'team1_40', 'team1_op_25', 'team1_op_40', 'team2',
       'team2_25', 'team2_40', 'team2_op_25', 'team2_op_40', 'tries1',
       'tries2', 'turnovers_conceded1', 'turnovers_conceded2',
       'turnovers_won1', 'turnovers_won2', 'week', 'yellow_cards1',
       'yellow_cards2'],
      dtype='object')

In [188]:
# There are couple of columns with , in it as a thousand seperators e.g. (meters carried)
for c in super_rugby_data.columns:
    super_rugby_data[c] = super_rugby_data[c].str.replace(',', "")

In [189]:
# convert relevent columns to int
col_int = ['carries1', 'carries2', 'clean_breaks1', 'clean_breaks2', 'conversions1',
           'conversions2', 'defenders_beaten1', 'defenders_beaten2','drop_goals1',
           'drop_goals2', 'kicks_in_play1', 'kicks_in_play2', 'lineouts_lost1', 
           'lineouts_lost2', 'lineouts_won1', 'lineouts_won2', 'mauls_won1', 
           'mauls_won2', 'meters_carried1', 'meters_carried2', 'missed_tackels1', 
           'missed_tackels2', 'offloads1', 'offloads2', 'passes1', 'passes2', 
           'penalties_conceded1', 'penalties_conceded2', 'penalty_goals1',
           'penalty_goals2', 'red_cards1', 'red_cards2', 'rucks_lost1', 'rucks_lost2', 
           'rucks_won1', 'rucks_won2', 'score1', 'score2', 'scrums_lost1', 
           'scrums_lost2', 'scrums_won1', 'scrums_won2', 'tackles1', 'tackles2', 
           'tries1', 'tries2', 'turnovers_conceded1', 'turnovers_conceded2', 
           'turnovers_won1', 'turnovers_won2', 'yellow_cards1', 'yellow_cards2', 'season']

In [190]:
for c in col_int:
    super_rugby_data[c] =  super_rugby_data[c].astype(int)

In [191]:
# floats are avaible % s, remove % sign and conver to float
col_float = ['conversion_accuracy1', 'conversion_accuracy2', 'drop_goal_accuracy1', 
             'drop_goal_accuracy2', 'overall_pos1', 'overall_pos2', 
             'penalty_goal_accuracy1', 'penalty_goal_accuracy2', 
             'team1_25', 'team1_40', 'team1_op_25', 'team1_op_40', 'team2_25', 
             'team2_40', 'team2_op_25', 'team2_op_40']

In [192]:
for c in col_float:
    super_rugby_data[c] =  super_rugby_data[c].str.replace('%',"")
    super_rugby_data[c] =  super_rugby_data[c].astype(float)

In [193]:
# names to string
col_names = ['team1', 'team2']

In [194]:
for c in col_names:
    super_rugby_data[c] =  super_rugby_data[c].astype('category')

In [195]:
# few transformations
super_rugby_data.week = super_rugby_data.week.replace({'week_':''}, regex = True)\
                            .astype(int)
super_rugby_data.match = super_rugby_data.match.replace({'match_':''}, regex = True)\
                            .astype(int)

In [196]:
# Data is cleaned
super_rugby_data.head()

,carries1,carries2,clean_breaks1,clean_breaks2,conversion_accuracy1,conversion_accuracy2,conversions1,conversions2,defenders_beaten1,defenders_beaten2,drop_goal_accuracy1,drop_goal_accuracy2,drop_goals1,drop_goals2,kicks_in_play1,kicks_in_play2,lineouts_lost1,lineouts_lost2,lineouts_won1,lineouts_won2,match,mauls_won1,mauls_won2,meters_carried1,meters_carried2,missed_tackels1,missed_tackels2,offloads1,offloads2,overall_pos1,overall_pos2,passes1,passes2,penalties_conceded1,penalties_conceded2,penalty_goal_accuracy1,penalty_goal_accuracy2,penalty_goals1,penalty_goals2,red_cards1,red_cards2,rucks_lost1,rucks_lost2,rucks_won1,rucks_won2,score1,score2,scrums_lost1,scrums_lost2,scrums_won1,scrums_won2,season,tackles1,tackles2,team1,team1_25,team1_40,team1_op_25,team1_op_40,team2,team2_25,team2_40,team2_op_25,team2_op_40,tries1,tries2,turnovers_conceded1,turnovers_conceded2,turnovers_won1,turnovers_won2,week,yellow_cards1,yellow_cards2
0,110,85,8,7,50.0,100.0,2,1,13,18,0.0,0.0,1,0,22,34,5,2,15,7,1,0,0,443,316,18,13,4,9,67.0,33.0,129,101,9,12,66.7,66.7,3,6,0,0,5,5,75,51,18,19,1,0,5,8,2012,74,115,Blues,0.0,0.0,0.0,0.0,Crusaders,0.0,0.0,0.0,0.0,2,1,18,14,0,0,1,0,0
1,69,132,11,1,0.0,0.0,2,1,15,10,0.0,0.0,0,1,28,27,2,4,5,15,2,0,0,331,312,10,15,6,8,67.0,33.0,79,144,11,10,42.9,66.7,7,6,0,0,4,4,49,109,19,17,0,0,6,5,2012,146,61,Brumbies,0.0,0.0,0.0,0.0,Force,0.0,0.0,0.0,0.0,2,1,11,7,0,0,1,0,0
2,78,86,4,7,0.0,100.0,0,1,17,17,100.0,0.0,1,0,27,20,2,5,12,6,3,0,0,333,348,17,17,3,5,0.0,100.0,85,136,11,13,71.4,40.0,7,5,0,0,2,2,62,59,18,13,1,1,5,8,2012,95,96,Bulls,0.0,0.0,0.0,0.0,Sharks,0.0,0.0,0.0,0.0,0,1,16,8,0,0,1,0,0
3,107,162,5,4,100.0,100.0,1,2,10,13,0.0,0.0,0,0,19,16,3,2,13,10,4,0,0,430,413,14,10,14,12,33.0,67.0,112,200,10,12,100.0,100.0,4,3,0,0,8,7,69,127,19,23,0,0,6,6,2012,176,104,Chiefs,0.0,0.0,0.0,0.0,Highlanders,0.0,0.0,0.0,0.0,1,2,15,17,0,0,1,0,0
4,86,84,3,4,0.0,100.0,0,1,7,13,0.0,50.0,1,2,16,21,5,1,10,4,5,0,0,304,259,13,7,9,5,0.0,100.0,130,125,12,17,81.8,71.4,11,7,0,0,6,6,65,70,27,25,0,1,4,5,2012,103,99,Lions,0.0,0.0,0.0,0.0,Cheetahs,0.0,0.0,0.0,0.0,0,1,14,12,0,0,1,0,2

In [208]:
# dealing NaNs created in the process
super_rugby_data.isnull().any()[super_rugby_data.isnull().any()==True]

overall_pos1    True
overall_pos2    True
team1_25        True
team1_40        True
team1_op_25     True
team1_op_40     True
team2_25        True
team2_40        True
team2_op_25     True
team2_op_40     True
dtype: bool

In [209]:
# all these NaNs can be treated as 0
col_NA = ['overall_pos1', 'overall_pos2', 'team1_25', 'team1_40', 'team1_op_25', 
          'team1_op_40', 'team2_25', 'team2_40', 'team2_op_25', 'team2_op_40']

for c in col_NA:
    super_rugby_data[c] = super_rugby_data[c].fillna(0)

In [213]:
# 2012 data do not have possetion info fof all terretories. 
# Most useful is the overall possetion

super_rugby_data.overall_pos1 = super_rugby_data.team1_25+super_rugby_data.team1_40+\
                                super_rugby_data.team1_op_25+super_rugby_data.team1_op_40+\
                                super_rugby_data.overall_pos1

super_rugby_data.overall_pos2 = super_rugby_data.team2_25+super_rugby_data.team2_40+\
                                super_rugby_data.team2_op_25+super_rugby_data.team2_op_40+\
                                super_rugby_data.overall_pos2

In [216]:
super_rugby_data.drop(['team1_25', 'team1_40', 'team1_op_25', 'team1_op_40', 
                       'team2_25', 'team2_40', 'team2_op_25', 'team2_op_40'], axis=1, 
                     inplace = True)

In [217]:
super_rugby_data.dtypes[super_rugby_data.dtypes == 'object']

Series([], dtype: object)

In [219]:
super_rugby_data.isnull().any()[super_rugby_data.isnull().any()==True]

Series([], dtype: bool)

In [220]:
super_rugby_data.shape

(749, 65)

In [222]:
super_rugby_data.head()

,carries1,carries2,clean_breaks1,clean_breaks2,conversion_accuracy1,conversion_accuracy2,conversions1,conversions2,defenders_beaten1,defenders_beaten2,drop_goal_accuracy1,drop_goal_accuracy2,drop_goals1,drop_goals2,kicks_in_play1,kicks_in_play2,lineouts_lost1,lineouts_lost2,lineouts_won1,lineouts_won2,match,mauls_won1,mauls_won2,meters_carried1,meters_carried2,missed_tackels1,missed_tackels2,offloads1,offloads2,overall_pos1,overall_pos2,passes1,passes2,penalties_conceded1,penalties_conceded2,penalty_goal_accuracy1,penalty_goal_accuracy2,penalty_goals1,penalty_goals2,red_cards1,red_cards2,rucks_lost1,rucks_lost2,rucks_won1,rucks_won2,score1,score2,scrums_lost1,scrums_lost2,scrums_won1,scrums_won2,season,tackles1,tackles2,team1,team2,tries1,tries2,turnovers_conceded1,turnovers_conceded2,turnovers_won1,turnovers_won2,week,yellow_cards1,yellow_cards2
0,110,85,8,7,50.0,100.0,2,1,13,18,0.0,0.0,1,0,22,34,5,2,15,7,1,0,0,443,316,18,13,4,9,67.0,33.0,129,101,9,12,66.7,66.7,3,6,0,0,5,5,75,51,18,19,1,0,5,8,2012,74,115,Blues,Crusaders,2,1,18,14,0,0,1,0,0
1,69,132,11,1,0.0,0.0,2,1,15,10,0.0,0.0,0,1,28,27,2,4,5,15,2,0,0,331,312,10,15,6,8,67.0,33.0,79,144,11,10,42.9,66.7,7,6,0,0,4,4,49,109,19,17,0,0,6,5,2012,146,61,Brumbies,Force,2,1,11,7,0,0,1,0,0
2,78,86,4,7,0.0,100.0,0,1,17,17,100.0,0.0,1,0,27,20,2,5,12,6,3,0,0,333,348,17,17,3,5,0.0,100.0,85,136,11,13,71.4,40.0,7,5,0,0,2,2,62,59,18,13,1,1,5,8,2012,95,96,Bulls,Sharks,0,1,16,8,0,0,1,0,0
3,107,162,5,4,100.0,100.0,1,2,10,13,0.0,0.0,0,0,19,16,3,2,13,10,4,0,0,430,413,14,10,14,12,33.0,67.0,112,200,10,12,100.0,100.0,4,3,0,0,8,7,69,127,19,23,0,0,6,6,2012,176,104,Chiefs,Highlanders,1,2,15,17,0,0,1,0,0
4,86,84,3,4,0.0,100.0,0,1,7,13,0.0,50.0,1,2,16,21,5,1,10,4,5,0,0,304,259,13,7,9,5,0.0,100.0,130,125,12,17,81.8,71.4,11,7,0,0,6,6,65,70,27,25,0,1,4,5,2012,103,99,Lions,Cheetahs,0,1,14,12,0,0,1,0,2

#

In [223]:
# convert data in to feather form for storage
super_rugby_data.to_feather('Data/super_rugby_data')